### ISSUE TITLE
Missing license field in package.json

### ISSUE THREAD

**Issue by Frank3K** [nolemmings/compare-json#2]
`npm` warns about the missing license field:

`npm WARN package.json compare-json@0.1.3 No license field.`

**Comment by nielskrijger** [comment]
Thanks.

We'll be looking at what License to use. 
Most likely MIT (https://opensource.org/licenses/MIT).

**Comment by Frank3K** [comment]
I think that would be a good choice, since both angular-translate and angular.js have that license. Looking at those two repos I think it would also be good to, besides updating `package.json`, include a `LICENSE` file (like [angular.js does](https://github.com/angular/angular.js/blob/master/LICENSE)).

**Comment by nielskrijger** [comment]
Fixed 1c7dff7da8574c2c6227be07aad620755e684971
