### ISSUE TITLE
Add option to process multiple files in groups

### ISSUE THREAD

**Issue by Frank3K** [nolemmings/compare-json#5]
I have my angular-translate files structured by section, e.g.:

```
index-nl.json
index-en.json
help-nl.json
help-en.json
about-nl.json
about-en.json
```

When running `comparejson *.json` every file is checked against every other file. What I would like is that all files with a common prefix ('index', 'help', or 'about') are checked against each other.

The best I can think of is to set some separator (in my case '-') such that groups can be formed. After forming groups, each groups can be processed by running `compareFiles` on the group. 

Do you have a better suggestion? I can do a PR if you want.

**Comment by nielskrijger** [comment]
Added feature in 5ead75d90ea17e7a672c54d9d80c3bb1eb260392
See README.

Any feedback is welcome, I'll be releasing 0.2.0 shortly.

Closing for now, feel free to reopen or submit new issue if it doesn't work as expected.

**Comment by Frank3K** [comment]
Thanks! I will review and test this tomorrow evening.

**Comment by Frank3K** [comment]
I have just tested this feature and it works as expected. Thanks again for adding it.

**Comment by benchaminaa** [comment]
Not sure I'm missing anything here in comparing multiple files in folder. When I run  >comparejson -e .\test\fixture\*.json  command I get following message of "No errors found". 

./test/fixture/*.json is complete                                                                                                                                                                                                               No errors found 

I was expecting modifications and missing elements as per documentation. Tried adding separator parameter like >comparejson -s="-" -e .\test\fixture\*.json, but didn't see any difference apart from comparison completed message is omitted. 
> comparejson -s="-"-e .\test\fixture\*.json
No errors found

any advice and suggestions will be greatly appreciated
